/*
 * Copyright © 2026 by tdbang.
 * All rights reserved.
 */

package com.tdbang.crm.entities;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;

import com.tdbang.crm.enums.ReportStatus;

/**
 * Metadata for each daily sales summary report generated by the batch job.
 */
@Getter
@Setter
@Entity
@Table(name = "daily_sales_report")
public class DailySalesReport {

    @Id
    @Column(name = "pk")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long pk;

    /** The date this report covers (one report per calendar day). */
    @Column(name = "report_date", nullable = false, unique = true)
    private LocalDate reportDate;

    @Column(name = "total_revenue", nullable = false, precision = 14, scale = 2)
    private BigDecimal totalRevenue = BigDecimal.ZERO;

    @Column(name = "total_orders", nullable = false)
    private Integer totalOrders = 0;

    @Column(name = "orders_created", nullable = false)
    private Integer ordersCreated = 0;

    @Column(name = "orders_approved", nullable = false)
    private Integer ordersApproved = 0;

    @Column(name = "orders_delivered", nullable = false)
    private Integer ordersDelivered = 0;

    @Column(name = "orders_canceled", nullable = false)
    private Integer ordersCanceled = 0;

    /** GridFS ObjectId (as string) of the generated Excel file in MongoDB. */
    @Column(name = "mongo_file_id", length = 200)
    private String mongoFileId;

    @Column(name = "file_name", length = 255)
    private String fileName;

    @Column(name = "status", nullable = false, length = 20)
    @Enumerated(EnumType.STRING)
    private ReportStatus status;

    @Column(name = "error_message", length = 500)
    private String errorMessage;

    @Column(name = "created_on")
    @Temporal(TemporalType.TIMESTAMP)
    @CreationTimestamp
    private Date createdOn;
}
