$kind: http-request
url: http://localhost:8080/oauth2/authorize?response_type=code&client_id=swagger-ui&redirect_uri=http://localhost:8080/swagger-ui/oauth2-redirect.html&scope=api:read
method: GET
queryParams:
  response_type: code
  client_id: swagger-ui
  redirect_uri: http://localhost:8080/swagger-ui/oauth2-redirect.html
  scope: api:read
auth:
  type: noauth
order: 4000
