CREATE TABLE IF NOT EXISTS contact (
pk BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
contact_name VARCHAR(255) NOT NULL,
salutation TINYINT NOT NULL,
mobile_phone VARCHAR(200),
email VARCHAR(200),
organization VARCHAR(255) NOT NULL,
dob DATE NULL,
lead_src TINYINT NOT NULL,
assigned_to BIGINT UNSIGNED NOT NULL,
creator BIGINT UNSIGNED NOT NULL,
address VARCHAR(255) NULL,
description VARCHAR(255) NULL,
created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (pk),
KEY contact_assigned_ind (assigned_to),
KEY contact_creator_ind (creator)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS user (
pk BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
username VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(200) NOT NULL,
email VARCHAR(200) NOT NULL UNIQUE,
phone VARCHAR(200),
is_manager tinyint(1) NOT NULL DEFAULT '0',
is_active tinyint(1) NOT NULL DEFAULT '0',
created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (pk)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS sales_order (
pk BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
subject VARCHAR(255) NOT NULL,
contact_fk BIGINT UNSIGNED NOT NULL,
status TINYINT NOT NULL,
total DECIMAL(14,2) NOT NULL,
assigned_to BIGINT UNSIGNED NOT NULL,
creator BIGINT UNSIGNED NOT NULL,
description VARCHAR(255) NULL,
created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (pk),
KEY sales_order_contact_ind (contact_fk),
KEY sales_order_assigned_ind (assigned_to),
KEY sales_order_creator_ind (creator)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;