CREATE TABLE IF NOT EXISTS audit_log (
id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
timestamp BIGINT,
username VARCHAR(200),
request_url VARCHAR(255) DEFAULT NULL,
action VARCHAR(100),
details VARCHAR(255) DEFAULT NULL,
description VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS contact_aud (
pk BIGINT UNSIGNED NOT NULL,
contact_name VARCHAR(255) NULL,
salutation TINYINT NULL,
mobile_phone VARCHAR(200),
email VARCHAR(200),
organization VARCHAR(255) NULL,
dob DATE NULL,
lead_src TINYINT NULL,
assigned_to BIGINT UNSIGNED NULL,
creator BIGINT UNSIGNED NULL,
address VARCHAR(255) NULL,
description VARCHAR(255) NULL,
created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
rev INTEGER NOT NULL,
rev_type TINYINT NOT NULL,
PRIMARY KEY (pk, rev)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS user_aud (
pk BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NULL,
first_name VARCHAR(255) NULL,
last_name VARCHAR(255) NULL,
username VARCHAR(100) NULL UNIQUE,
password VARCHAR(200) NULL,
email VARCHAR(200) NOT NULL UNIQUE,
phone VARCHAR(200),
is_admin tinyint(1) NOT NULL DEFAULT '0',
is_active tinyint(1) NOT NULL DEFAULT '0',
is_staff tinyint(1) NOT NULL DEFAULT '0',
created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
rev INTEGER NOT NULL,
rev_type TINYINT NOT NULL,
PRIMARY KEY (pk, rev)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS sales_order_aud (
pk BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
subject VARCHAR(255) NULL,
contact_fk BIGINT UNSIGNED NULL,
status TINYINT NULL,
total DECIMAL(14,2) NULL,
assigned_to BIGINT UNSIGNED NULL,
creator BIGINT UNSIGNED NULL,
description VARCHAR(255) NULL,
created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
rev INTEGER NOT NULL,
rev_type TINYINT NOT NULL,
PRIMARY KEY (pk, rev)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS product_aud (
pk BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NULL,
price DECIMAL(14,3) NULL,
is_active tinyint(1) NOT NULL DEFAULT '0',
description VARCHAR(255) NULL,
created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
rev INTEGER NOT NULL,
rev_type TINYINT NOT NULL,
PRIMARY KEY (pk, rev)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
