CREATE TABLE IF NOT EXISTS note (
pk BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
entity_type VARCHAR(50) NOT NULL,
entity_fk BIGINT UNSIGNED NOT NULL,
note_type VARCHAR(30) NOT NULL,
content TEXT NOT NULL,
created_by BIGINT UNSIGNED NOT NULL,
created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (pk),
KEY note_entity_ind (entity_type, entity_fk),
CONSTRAINT fk_note_created_by FOREIGN KEY (created_by) REFERENCES user(pk)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS sales_order_item (
pk BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
sales_order_fk BIGINT UNSIGNED NOT NULL,
product_fk BIGINT UNSIGNED NOT NULL,
quantity INT NOT NULL DEFAULT 1,
unit_price DECIMAL(14,3) NOT NULL,
discount DECIMAL(5,2) NOT NULL DEFAULT 0,
line_total DECIMAL(14,2) NOT NULL,
sort_order INT NOT NULL DEFAULT 0,
created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (pk),
KEY soi_order_ind (sales_order_fk),
CONSTRAINT fk_soi_order FOREIGN KEY (sales_order_fk)
  REFERENCES sales_order(pk) ON DELETE CASCADE,
CONSTRAINT fk_soi_product FOREIGN KEY (product_fk)
  REFERENCES product(pk)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS task (
pk BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
title VARCHAR(255) NOT NULL,
task_type VARCHAR(30) NOT NULL,
entity_type VARCHAR(50) NULL,
entity_fk BIGINT UNSIGNED NULL,
status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
priority VARCHAR(10) NOT NULL DEFAULT 'MEDIUM',
due_date DATE NULL,
description TEXT NULL,
assigned_to BIGINT UNSIGNED NOT NULL,
created_by BIGINT UNSIGNED NOT NULL,
created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (pk),
KEY task_entity_ind (entity_type, entity_fk),
KEY task_assigned_ind (assigned_to),
KEY task_status_ind (status),
CONSTRAINT fk_task_assigned_to FOREIGN KEY (assigned_to) REFERENCES user(pk),
CONSTRAINT fk_task_created_by FOREIGN KEY (created_by) REFERENCES user(pk)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
